PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>
PREFIX chebidb: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chebirel: <http://purl.obolibrary.org/obo/CHEBI#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX reactome: <http://www.reactome.org/biopax/91/48887#>
PREFIX abstraction:<http://abstraction/#>

SELECT DISTINCT ?Pathway1anc ?Pathway2anc
#CONSTRUCT {
#  ?Pathway1 abstraction:NextStepPathway ?Pathway2anc .
#}
WHERE {  
  ?Pathway1 rdf:type bp3:Pathway .
  ?Pathway1 bp3:pathwayOrder ?PathwayStep1 .
  ?pathwayStep1 bp3:nextStep ?PathwayStep2 .
  ?Pathway2 bp3:pathwayOrder ?PathwayStep2 .
  ?Pathway2 rdf:type bp3:Pathway .
  FILTER (?Pathway1 != ?Pathway2) # not logically-necessary, but might improve performances
  ?Pathway1anc bp3:pathwayComponent* ?Pathway1 .
  ?Pathway1anc rdf:type bp3:Pathway .
  ?Pathway2anc bp3:pathwayComponent* ?Pathway2 .
  ?Pathway2anc rdf:type bp3:Pathway .
  FILTER NOT EXISTS { ?Pathway2anc bp3:pathwayComponent* ?Pathway1anc }
  FILTER NOT EXISTS { ?Pathway1anc bp3:pathwayComponent* ?Pathway2anc }
}
